#!/bin/bash
#
# chkconfig: 345 70 30
# processname: CopyConsole

# Source function library.
. /etc/init.d/functions

RETVAL=0
prog="CopyConsole"
LOCKFILE=/var/lock/subsys/$prog

# Declare variables for CopyConsole
COPY_DIR=/root/copy/x86_64
CopyConsole=$COPY_DIR/CopyConsole

start() {
        echo -n "Starting $prog: "
        $CopyConsole -daemon
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch $LOCKFILE
        echo
        return $RETVAL
}

stop() {
        echo -n "Shutting down $prog: "
        killall CopyConsole
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
        echo
        return $RETVAL
}

status() {
        echo -n "Checking $prog status: "
        cat /root/.copy/status.txt
        RETVAL=$?
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
